services:
  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    network_mode: host
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro

